#!/usr/bin/env python3
"""Bundle roblox/src into StudioInstaller.lua.

The output is a single script that can be pasted into Roblox Studio's
command bar; it recreates the whole Rojo tree as Script/LocalScript/
ModuleScript instances. Re-run this after editing anything in src/.
"""

import os

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "src")
OUT = os.path.join(ROOT, "StudioInstaller.lua")

TARGETS = {
    "server": ["ServerScriptService", "RivalsShooter"],
    "shared": ["ReplicatedStorage", "RivalsShared"],
    "client": ["StarterPlayer", "StarterPlayerScripts", "RivalsClient"],
}


def class_and_name(filename):
    if filename.endswith(".server.luau"):
        return "Script", filename[: -len(".server.luau")]
    if filename.endswith(".client.luau"):
        return "LocalScript", filename[: -len(".client.luau")]
    if filename.endswith(".luau"):
        return "ModuleScript", filename[: -len(".luau")]
    raise ValueError(f"unexpected file: {filename}")


def long_string(text):
    """Wrap text in Lua long brackets, picking an =-level not present in it."""
    level = 1
    while f"]{'=' * level}]" in text or text.endswith("]" + "=" * level):
        level += 1
    eq = "=" * level
    return f"[{eq}[\n{text}]{eq}]"


def main():
    entries = []
    for subdir, parent in TARGETS.items():
        dir_path = os.path.join(SRC, subdir)
        for filename in sorted(os.listdir(dir_path)):
            with open(os.path.join(dir_path, filename), encoding="utf-8") as f:
                source = f.read()
            class_name, name = class_and_name(filename)
            parent_lua = ", ".join(f'"{p}"' for p in parent)
            entries.append(
                "\t{\n"
                f'\t\tparent = {{ {parent_lua} }},\n'
                f'\t\tname = "{name}",\n'
                f'\t\tclass = "{class_name}",\n'
                f"\t\tsource = {long_string(source)},\n"
                "\t},"
            )

    scripts_table = "\n".join(entries)
    out = f"""\
-- Rivals-style shooter — one-shot installer (generated by build_installer.py).
-- HOW TO USE:
--   1. Open your place in Roblox Studio.
--   2. View > Command Bar.
--   3. Paste this ENTIRE file into the command bar and press Enter.
--   4. Press Play to test (Test > Clients and Servers with 2+ players for PvP).
-- Re-running is safe: the previous install is replaced.

local function resolvePath(names)
	local node = game
	for _, name in ipairs(names) do
		if node == game then
			node = game:GetService(name)
		else
			local child = node:FindFirstChild(name)
			if not child then
				child = Instance.new("Folder")
				child.Name = name
				child.Parent = node
			end
			node = child
		end
	end
	return node
end

local function wipe(parentNames, name)
	local node = game
	for _, n in ipairs(parentNames) do
		node = (node == game) and game:GetService(n) or node:FindFirstChild(n)
		if not node then
			return
		end
	end
	local old = node:FindFirstChild(name)
	if old then
		old:Destroy()
	end
end

wipe({{ "ServerScriptService" }}, "RivalsShooter")
wipe({{ "ReplicatedStorage" }}, "RivalsShared")
wipe({{ "ReplicatedStorage" }}, "RivalsRemotes")
wipe({{ "StarterPlayer", "StarterPlayerScripts" }}, "RivalsClient")
wipe({{ "Workspace" }}, "RivalsMap")

local scripts = {{
{scripts_table}
}}

for _, def in ipairs(scripts) do
	local inst = Instance.new(def.class)
	inst.Name = def.name
	inst.Source = def.source
	inst.Parent = resolvePath(def.parent)
end

print(("[Rivals Shooter] Installed %d scripts. Press Play to test!"):format(#scripts))
"""
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {OUT} ({len(entries)} scripts)")


if __name__ == "__main__":
    main()
