-- Rivals-style shooter — one-shot installer (generated by build_installer.py).
-- HOW TO USE:
--   1. Open your place in Roblox Studio.
--   2. View > Command Bar.
--   3. Paste this ENTIRE file into the command bar and press Enter.
--   4. Press Play to test (Test > Clients and Servers with 2+ players for PvP).
-- Re-running is safe: the previous install is replaced.

local function resolvePath(names)
	local node = game
	for _, name in ipairs(names) do
		if node == game then
			node = game:GetService(name)
		else
			local child = node:FindFirstChild(name)
			if not child then
				child = Instance.new("Folder")
				child.Name = name
				child.Parent = node
			end
			node = child
		end
	end
	return node
end

local function wipe(parentNames, name)
	local node = game
	for _, n in ipairs(parentNames) do
		node = (node == game) and game:GetService(n) or node:FindFirstChild(n)
		if not node then
			return
		end
	end
	local old = node:FindFirstChild(name)
	if old then
		old:Destroy()
	end
end

wipe({ "ServerScriptService" }, "RivalsShooter")
wipe({ "ReplicatedStorage" }, "RivalsShared")
wipe({ "ReplicatedStorage" }, "RivalsRemotes")
wipe({ "StarterPlayer", "StarterPlayerScripts" }, "RivalsClient")
wipe({ "Workspace" }, "RivalsMap")

local scripts = {
	{
		parent = { "ServerScriptService", "RivalsShooter" },
		name = "CombatServer",
		class = "Script",
		source = [=[
-- Server-authoritative combat: validates every shot (rate, ammo, origin,
-- team) and applies damage. Clients only ever *request* a shot.
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local shared = ReplicatedStorage:WaitForChild("RivalsShared")
local Remotes = require(shared:WaitForChild("Remotes"))
local WeaponConfig = require(shared:WaitForChild("WeaponConfig"))

local fireRemote = Remotes.get("FireWeapon")
local reloadRemote = Remotes.get("Reload")
local hitConfirm = Remotes.get("HitConfirm")

local MAX_ORIGIN_DRIFT = 12 -- studs the claimed muzzle may differ from the head
local RATE_TOLERANCE = 0.7 -- fraction of the fire interval we accept, for latency

-- state[player][weaponName] = { ammo, lastShot, reloading }
local state = {}

local function weaponState(player, weaponName, cfg)
	local perPlayer = state[player]
	if not perPlayer then
		perPlayer = {}
		state[player] = perPlayer
	end
	local ws = perPlayer[weaponName]
	if not ws then
		ws = { ammo = cfg.magSize, lastShot = 0, reloading = false }
		perPlayer[weaponName] = ws
	end
	return ws
end

local function findTool(player, weaponName)
	local function scan(container)
		if not container then
			return nil
		end
		for _, child in container:GetChildren() do
			if child:IsA("Tool") and child:GetAttribute("WeaponName") == weaponName then
				return child
			end
		end
		return nil
	end
	return scan(player.Character) or scan(player:FindFirstChild("Backpack"))
end

local function syncTool(player, weaponName, ws)
	local tool = findTool(player, weaponName)
	if tool then
		tool:SetAttribute("Ammo", ws.ammo)
		tool:SetAttribute("Reloading", ws.reloading)
	end
end

fireRemote.OnServerEvent:Connect(function(player, weaponName, origin, dirs)
	if type(weaponName) ~= "string" or typeof(origin) ~= "Vector3" or type(dirs) ~= "table" then
		return
	end
	local cfg = WeaponConfig[weaponName]
	if not cfg then
		return
	end
	local character = player.Character
	local humanoid = character and character:FindFirstChildOfClass("Humanoid")
	local head = character and character:FindFirstChild("Head")
	if not (humanoid and humanoid.Health > 0 and head) then
		return
	end
	if (origin - head.Position).Magnitude > MAX_ORIGIN_DRIFT then
		return
	end

	local ws = weaponState(player, weaponName, cfg)
	local now = os.clock()
	if ws.reloading or ws.ammo <= 0 then
		return
	end
	if now - ws.lastShot < (1 / cfg.fireRate) * RATE_TOLERANCE then
		return
	end
	ws.lastShot = now
	ws.ammo -= 1
	syncTool(player, weaponName, ws)

	local params = RaycastParams.new()
	params.FilterDescendantsInstances = { character }
	params.FilterType = Enum.RaycastFilterType.Exclude

	local totalDamage = 0
	local anyHeadshot = false
	local pelletCount = math.min(#dirs, cfg.pellets)
	for i = 1, pelletCount do
		local dir = dirs[i]
		if typeof(dir) == "Vector3" and dir.Magnitude > 0 then
			local result = workspace:Raycast(origin, dir.Unit * cfg.range, params)
			if result then
				local model = result.Instance:FindFirstAncestorOfClass("Model")
				local victimHumanoid = model and model:FindFirstChildOfClass("Humanoid")
				if victimHumanoid and victimHumanoid.Health > 0 then
					local victimPlayer = Players:GetPlayerFromCharacter(model)
					local friendly = victimPlayer
						and victimPlayer.Team ~= nil
						and victimPlayer.Team == player.Team
					if not friendly then
						local isHead = result.Instance.Name == "Head"
						local damage = cfg.damage * (isHead and cfg.headshot or 1)
						victimHumanoid:SetAttribute("LastDamagerUserId", player.UserId)
						victimHumanoid:SetAttribute("LastDamagerWeapon", cfg.displayName)
						victimHumanoid:SetAttribute("LastDamageHeadshot", isHead)
						victimHumanoid:SetAttribute("LastDamageTime", os.clock())
						victimHumanoid:TakeDamage(damage)
						totalDamage += damage
						anyHeadshot = anyHeadshot or isHead
					end
				end
			end
		end
	end

	if totalDamage > 0 then
		hitConfirm:FireClient(player, totalDamage, anyHeadshot)
	end
end)

reloadRemote.OnServerEvent:Connect(function(player, weaponName)
	if type(weaponName) ~= "string" then
		return
	end
	local cfg = WeaponConfig[weaponName]
	if not cfg then
		return
	end
	local ws = weaponState(player, weaponName, cfg)
	if ws.reloading or ws.ammo >= cfg.magSize then
		return
	end
	ws.reloading = true
	syncTool(player, weaponName, ws)
	task.delay(cfg.reloadTime, function()
		if state[player] and state[player][weaponName] == ws then
			ws.reloading = false
			ws.ammo = cfg.magSize
			syncTool(player, weaponName, ws)
		end
	end)
end)

local function resetPlayer(player)
	state[player] = nil
end

Players.PlayerAdded:Connect(function(player)
	player.CharacterAdded:Connect(function()
		resetPlayer(player) -- fresh mags every spawn
	end)
end)
Players.PlayerRemoving:Connect(resetPlayer)
]=],
	},
	{
		parent = { "ServerScriptService", "RivalsShooter" },
		name = "GameManager",
		class = "Script",
		source = [=[
-- Teams, kill credit, heal-on-kill, killfeed, and the round loop
-- (team deathmatch: first team to the kill target, or highest when time runs out).
local Players = game:GetService("Players")
local Teams = game:GetService("Teams")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local shared = ReplicatedStorage:WaitForChild("RivalsShared")
local Remotes = require(shared:WaitForChild("Remotes"))

local killFeed = Remotes.get("KillFeed")
local roundState = Remotes.get("RoundState")

local ROUND_TIME = 300
local KILL_TARGET = 40
local KILL_HEAL = 35
local KILL_CREDIT_WINDOW = 6 -- seconds after last damage that a death still counts

local function ensureTeam(name, brickColor)
	local team = Teams:FindFirstChild(name)
	if not team then
		team = Instance.new("Team")
		team.Name = name
		team.TeamColor = brickColor
		team.Parent = Teams
	end
	team.AutoAssignable = true
	return team
end
ensureTeam("Red", BrickColor.new("Bright red"))
ensureTeam("Blue", BrickColor.new("Bright blue"))

local scores = { Red = 0, Blue = 0 }
local roundEndsAt = 0
local roundOver = false

local function broadcast(stateName, winner)
	roundState:FireAllClients({
		red = scores.Red,
		blue = scores.Blue,
		timeLeft = math.max(0, math.floor(roundEndsAt - os.clock())),
		state = stateName,
		winner = winner,
		target = KILL_TARGET,
	})
end

local function bumpStat(player, statName)
	local stats = player:FindFirstChild("leaderstats")
	local stat = stats and stats:FindFirstChild(statName)
	if stat then
		stat.Value += 1
	end
end

local function onDied(player, humanoid)
	bumpStat(player, "Deaths")

	local killerId = humanoid:GetAttribute("LastDamagerUserId")
	local damageTime = humanoid:GetAttribute("LastDamageTime")
	local weapon = humanoid:GetAttribute("LastDamagerWeapon")
	local headshot = humanoid:GetAttribute("LastDamageHeadshot") == true

	local killer
	if killerId and damageTime and os.clock() - damageTime <= KILL_CREDIT_WINDOW then
		killer = Players:GetPlayerByUserId(killerId)
	end

	if killer and killer ~= player then
		bumpStat(killer, "Kills")
		local teamName = killer.Team and killer.Team.Name
		if not roundOver and teamName and scores[teamName] then
			scores[teamName] += 1
		end
		-- Rivals-style: kills top you back up
		local killerHumanoid = killer.Character and killer.Character:FindFirstChildOfClass("Humanoid")
		if killerHumanoid and killerHumanoid.Health > 0 then
			killerHumanoid.Health = math.min(killerHumanoid.MaxHealth, killerHumanoid.Health + KILL_HEAL)
		end
		killFeed:FireAllClients(killer.Name, player.Name, weapon or "?", headshot)
	else
		killFeed:FireAllClients(nil, player.Name, nil, false)
	end
end

Players.PlayerAdded:Connect(function(player)
	player.CharacterAdded:Connect(function(character)
		local humanoid = character:WaitForChild("Humanoid")
		humanoid.Died:Once(function()
			onDied(player, humanoid)
		end)
	end)
end)

task.spawn(function()
	while true do
		scores.Red, scores.Blue = 0, 0
		roundOver = false
		roundEndsAt = os.clock() + ROUND_TIME
		while os.clock() < roundEndsAt and scores.Red < KILL_TARGET and scores.Blue < KILL_TARGET do
			broadcast("playing")
			task.wait(1)
		end
		roundOver = true
		local winner
		if scores.Red == scores.Blue then
			winner = "Draw"
		else
			winner = scores.Red > scores.Blue and "Red" or "Blue"
		end
		for _ = 1, 8 do
			broadcast("over", winner)
			task.wait(1)
		end
		for _, player in Players:GetPlayers() do
			player:LoadCharacter()
		end
	end
end)
]=],
	},
	{
		parent = { "ServerScriptService", "RivalsShooter" },
		name = "MapBuilder",
		class = "Script",
		source = [=[
-- Builds a symmetric PvP arena at runtime so the game works in any place,
-- including an empty baseplate. Red spawns at -X, Blue at +X.
local Lighting = game:GetService("Lighting")

local ARENA = 260
local WALL_HEIGHT = 40

local map = Instance.new("Folder")
map.Name = "RivalsMap"

local function newPart(props)
	local p = Instance.new(props.wedge and "WedgePart" or "Part")
	p.Anchored = true
	p.TopSurface = Enum.SurfaceType.Smooth
	p.BottomSurface = Enum.SurfaceType.Smooth
	p.Size = props.size
	p.CFrame = props.cframe or CFrame.new(props.position)
	p.Color = props.color or Color3.fromRGB(99, 95, 98)
	p.Material = props.material or Enum.Material.SmoothPlastic
	p.Name = props.name or "MapPart"
	p.Parent = map
	return p
end

-- Floor and perimeter walls
newPart({
	name = "Floor",
	size = Vector3.new(ARENA, 1, ARENA),
	position = Vector3.new(0, 0.5, 0),
	color = Color3.fromRGB(46, 46, 50),
	material = Enum.Material.Slate,
})
newPart({
	name = "CenterStripe",
	size = Vector3.new(2, 0.1, ARENA),
	position = Vector3.new(0, 1.06, 0),
	color = Color3.fromRGB(255, 255, 255),
	material = Enum.Material.Neon,
})
for _, def in {
	{ Vector3.new(ARENA, WALL_HEIGHT, 2), Vector3.new(0, WALL_HEIGHT / 2, ARENA / 2) },
	{ Vector3.new(ARENA, WALL_HEIGHT, 2), Vector3.new(0, WALL_HEIGHT / 2, -ARENA / 2) },
	{ Vector3.new(2, WALL_HEIGHT, ARENA), Vector3.new(ARENA / 2, WALL_HEIGHT / 2, 0) },
	{ Vector3.new(2, WALL_HEIGHT, ARENA), Vector3.new(-ARENA / 2, WALL_HEIGHT / 2, 0) },
} do
	newPart({
		name = "Wall",
		size = def[1],
		position = def[2],
		color = Color3.fromRGB(30, 30, 34),
		material = Enum.Material.Metal,
	})
end

-- Mirrored cover blocks so neither side has an advantage
local rng = Random.new(7)
for _ = 1, 16 do
	local sx = rng:NextNumber(4, 10)
	local sy = rng:NextNumber(4, 9)
	local sz = rng:NextNumber(4, 10)
	local x = rng:NextNumber(18, 110)
	local z = rng:NextNumber(-115, 115)
	local shade = rng:NextInteger(60, 90)
	for _, side in { -1, 1 } do
		newPart({
			name = "Cover",
			size = Vector3.new(sx, sy, sz),
			position = Vector3.new(x * side, 1 + sy / 2, z),
			color = Color3.fromRGB(shade, shade, shade + 8),
			material = Enum.Material.Concrete,
		})
	end
end

-- Center platform with four sloped ramps for high-ground fights
newPart({
	name = "CenterPlatform",
	size = Vector3.new(30, 1, 30),
	position = Vector3.new(0, 12.5, 0),
	color = Color3.fromRGB(70, 70, 78),
	material = Enum.Material.Metal,
})
for _, dir in { Vector3.new(1, 0, 0), Vector3.new(-1, 0, 0), Vector3.new(0, 0, 1), Vector3.new(0, 0, -1) } do
	local bottom = dir * 42 + Vector3.new(0, 1, 0)
	local top = dir * 15 + Vector3.new(0, 12.5, 0)
	local mid = (bottom + top) / 2
	local length = (top - bottom).Magnitude
	newPart({
		name = "Ramp",
		size = Vector3.new(10, 1, length + 2),
		cframe = CFrame.lookAt(mid, top),
		color = Color3.fromRGB(70, 70, 78),
		material = Enum.Material.Metal,
	})
end

-- Jump pads: step on one, get launched
for _, pos in {
	Vector3.new(55, 1.25, 55),
	Vector3.new(55, 1.25, -55),
	Vector3.new(-55, 1.25, 55),
	Vector3.new(-55, 1.25, -55),
} do
	local pad = newPart({
		name = "JumpPad",
		size = Vector3.new(6, 0.5, 6),
		position = pos,
		color = Color3.fromRGB(80, 255, 120),
		material = Enum.Material.Neon,
	})
	local ready = {}
	pad.Touched:Connect(function(hit)
		local model = hit:FindFirstAncestorOfClass("Model")
		local root = model and model:FindFirstChild("HumanoidRootPart")
		if root and (not ready[root] or os.clock() - ready[root] > 0.5) then
			ready[root] = os.clock()
			local v = root.AssemblyLinearVelocity
			root.AssemblyLinearVelocity = Vector3.new(v.X, 90, v.Z)
		end
	end)
end

-- Team spawns at opposite ends
local function spawnPad(x, z, teamColor)
	local s = Instance.new("SpawnLocation")
	s.Size = Vector3.new(6, 1, 6)
	s.Position = Vector3.new(x, 1.5, z)
	s.Anchored = true
	s.Neutral = false
	s.TeamColor = teamColor
	s.Duration = 4
	s.Color = teamColor.Color
	s.Material = Enum.Material.Neon
	s.Transparency = 0.4
	local decal = s:FindFirstChildOfClass("Decal")
	if decal then
		decal:Destroy()
	end
	s.Parent = map
end
for i = -2, 2 do
	spawnPad(-118, i * 22, BrickColor.new("Bright red"))
	spawnPad(118, i * 22, BrickColor.new("Bright blue"))
end

-- Remove any pre-existing neutral spawns so players always spawn on team pads
for _, child in workspace:GetChildren() do
	if child:IsA("SpawnLocation") then
		child:Destroy()
	end
end

map.Parent = workspace

Lighting.ClockTime = 14.5
Lighting.Brightness = 2.5
]=],
	},
	{
		parent = { "ServerScriptService", "RivalsShooter" },
		name = "PlayerSetup",
		class = "Script",
		source = [=[
-- Spawning: fast base movement, leaderstats, and the weapon loadout.
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local shared = ReplicatedStorage:WaitForChild("RivalsShared")
local WeaponConfig = require(shared:WaitForChild("WeaponConfig"))

Players.RespawnTime = 2.5

local sortedWeapons = {}
for key, cfg in WeaponConfig do
	table.insert(sortedWeapons, { key = key, cfg = cfg })
end
table.sort(sortedWeapons, function(a, b)
	return a.cfg.slot < b.cfg.slot
end)

local function buildTool(key, cfg)
	local tool = Instance.new("Tool")
	tool.Name = cfg.displayName
	tool.CanBeDropped = false
	tool.ToolTip = cfg.displayName
	tool:SetAttribute("WeaponName", key)
	tool:SetAttribute("Ammo", cfg.magSize)
	tool:SetAttribute("Reloading", false)

	local handle = Instance.new("Part")
	handle.Name = "Handle"
	handle.Size = Vector3.new(0.5, 0.5, 2.2)
	handle.Color = Color3.fromRGB(40, 40, 45)
	handle.Material = Enum.Material.Metal
	handle.CanCollide = false
	handle.Massless = true
	handle.Parent = tool

	return tool
end

local function onCharacterAdded(player, character)
	local humanoid = character:WaitForChild("Humanoid")
	humanoid.WalkSpeed = 24
	humanoid.UseJumpPower = true
	humanoid.JumpPower = 55

	local backpack = player:WaitForChild("Backpack")
	local firstTool
	for _, entry in sortedWeapons do
		local tool = buildTool(entry.key, entry.cfg)
		tool.Parent = backpack
		firstTool = firstTool or tool
	end

	task.delay(0.2, function()
		if firstTool and firstTool.Parent == backpack and humanoid.Health > 0 then
			humanoid:EquipTool(firstTool)
		end
	end)
end

local function onPlayerAdded(player)
	local stats = Instance.new("Folder")
	stats.Name = "leaderstats"
	local kills = Instance.new("IntValue")
	kills.Name = "Kills"
	kills.Parent = stats
	local deaths = Instance.new("IntValue")
	deaths.Name = "Deaths"
	deaths.Parent = stats
	stats.Parent = player

	player.CharacterAdded:Connect(function(character)
		onCharacterAdded(player, character)
	end)
	if player.Character then
		onCharacterAdded(player, player.Character)
	end
end

Players.PlayerAdded:Connect(onPlayerAdded)
for _, player in Players:GetPlayers() do
	onPlayerAdded(player)
end
]=],
	},
	{
		parent = { "ReplicatedStorage", "RivalsShared" },
		name = "Remotes",
		class = "ModuleScript",
		source = [=[
-- Single access point for RemoteEvents. The server creates them on demand;
-- clients wait for them to replicate.
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")

local FOLDER_NAME = "RivalsRemotes"

local Remotes = {}

function Remotes.get(name)
	if RunService:IsServer() then
		local folder = ReplicatedStorage:FindFirstChild(FOLDER_NAME)
		if not folder then
			folder = Instance.new("Folder")
			folder.Name = FOLDER_NAME
			folder.Parent = ReplicatedStorage
		end
		local remote = folder:FindFirstChild(name)
		if not remote then
			remote = Instance.new("RemoteEvent")
			remote.Name = name
			remote.Parent = folder
		end
		return remote
	else
		local folder = ReplicatedStorage:WaitForChild(FOLDER_NAME)
		return folder:WaitForChild(name)
	end
end

return Remotes
]=],
	},
	{
		parent = { "ReplicatedStorage", "RivalsShared" },
		name = "WeaponConfig",
		class = "ModuleScript",
		source = [=[
-- Weapon balance for the Rivals-style shooter. All damage numbers assume 100 HP.
-- fireRate is shots per second, spread is in degrees, range in studs.
return {
	AssaultRifle = {
		displayName = "AK-77",
		slot = 1,
		damage = 21,
		headshot = 1.6,
		fireRate = 8.5,
		magSize = 30,
		reloadTime = 1.7,
		spread = 1.1,
		range = 500,
		pellets = 1,
		auto = true,
	},
	Shotgun = {
		displayName = "Riot Shotgun",
		slot = 2,
		damage = 11,
		headshot = 1.4,
		fireRate = 1.8,
		magSize = 6,
		reloadTime = 2.2,
		spread = 5.5,
		range = 150,
		pellets = 8,
		auto = false,
	},
	Sniper = {
		displayName = "DMR-9",
		slot = 3,
		damage = 85,
		headshot = 2.0,
		fireRate = 1.1,
		magSize = 4,
		reloadTime = 2.4,
		spread = 0.05,
		range = 1200,
		pellets = 1,
		auto = false,
	},
}
]=],
	},
	{
		parent = { "StarterPlayer", "StarterPlayerScripts", "RivalsClient" },
		name = "HUD",
		class = "LocalScript",
		source = [=[
-- HUD: health bar, ammo counter, team scores + round timer, killfeed,
-- and the round-over banner.
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")

local player = Players.LocalPlayer

local shared = ReplicatedStorage:WaitForChild("RivalsShared")
local Remotes = require(shared:WaitForChild("Remotes"))

local killFeed = Remotes.get("KillFeed")
local roundState = Remotes.get("RoundState")

local RED = Color3.fromRGB(255, 75, 75)
local BLUE = Color3.fromRGB(85, 140, 255)
local WHITE = Color3.fromRGB(240, 240, 240)

local gui = Instance.new("ScreenGui")
gui.Name = "RivalsHUD"
gui.ResetOnSpawn = false
gui.Parent = player:WaitForChild("PlayerGui")

local function label(props)
	local l = Instance.new("TextLabel")
	l.BackgroundTransparency = props.bg and 0.35 or 1
	l.BackgroundColor3 = Color3.new(0, 0, 0)
	l.BorderSizePixel = 0
	l.Font = Enum.Font.GothamBold
	l.TextColor3 = props.color or WHITE
	l.TextSize = props.textSize or 18
	l.TextStrokeTransparency = 0.5
	l.Text = props.text or ""
	l.Size = props.size
	l.Position = props.position
	l.AnchorPoint = props.anchor or Vector2.new(0, 0)
	l.TextXAlignment = props.xAlign or Enum.TextXAlignment.Center
	l.Parent = props.parent or gui
	return l
end

-- Health bar (bottom left) ------------------------------------------------
local healthBack = Instance.new("Frame")
healthBack.Size = UDim2.fromOffset(260, 24)
healthBack.Position = UDim2.new(0, 24, 1, -56)
healthBack.BackgroundColor3 = Color3.fromRGB(20, 20, 24)
healthBack.BackgroundTransparency = 0.25
healthBack.BorderSizePixel = 0
healthBack.Parent = gui
Instance.new("UICorner", healthBack).CornerRadius = UDim.new(0, 6)

local healthFill = Instance.new("Frame")
healthFill.Size = UDim2.new(1, 0, 1, 0)
healthFill.BackgroundColor3 = Color3.fromRGB(90, 220, 110)
healthFill.BorderSizePixel = 0
healthFill.Parent = healthBack
Instance.new("UICorner", healthFill).CornerRadius = UDim.new(0, 6)

local healthText = label({
	parent = healthBack,
	size = UDim2.new(1, 0, 1, 0),
	position = UDim2.new(0, 0, 0, 0),
	text = "100",
	textSize = 16,
})

local function updateHealth(humanoid)
	local frac = math.clamp(humanoid.Health / humanoid.MaxHealth, 0, 1)
	healthFill.Size = UDim2.new(frac, 0, 1, 0)
	healthFill.BackgroundColor3 = Color3.fromHSV(0.33 * frac, 0.8, 0.9)
	healthText.Text = tostring(math.floor(humanoid.Health + 0.5))
end

-- Ammo (bottom right) -----------------------------------------------------
local ammoLabel = label({
	size = UDim2.fromOffset(220, 40),
	position = UDim2.new(1, -244, 1, -72),
	text = "",
	textSize = 30,
	xAlign = Enum.TextXAlignment.Right,
})

local equippedTool
local ammoConnections = {}

local function clearAmmoConnections()
	for _, c in ammoConnections do
		c:Disconnect()
	end
	table.clear(ammoConnections)
end

local function updateAmmo()
	if not equippedTool then
		ammoLabel.Text = ""
		return
	end
	if equippedTool:GetAttribute("Reloading") then
		ammoLabel.Text = "RELOADING…"
	else
		ammoLabel.Text = tostring(equippedTool:GetAttribute("Ammo") or 0)
	end
end

local function setEquipped(tool)
	clearAmmoConnections()
	equippedTool = tool
	if tool then
		table.insert(ammoConnections, tool:GetAttributeChangedSignal("Ammo"):Connect(updateAmmo))
		table.insert(ammoConnections, tool:GetAttributeChangedSignal("Reloading"):Connect(updateAmmo))
	end
	updateAmmo()
end

-- Scoreboard + timer (top center) -----------------------------------------
local scoreFrame = Instance.new("Frame")
scoreFrame.Size = UDim2.fromOffset(300, 36)
scoreFrame.Position = UDim2.new(0.5, 0, 0, 8)
scoreFrame.AnchorPoint = Vector2.new(0.5, 0)
scoreFrame.BackgroundColor3 = Color3.fromRGB(20, 20, 24)
scoreFrame.BackgroundTransparency = 0.35
scoreFrame.BorderSizePixel = 0
scoreFrame.Parent = gui
Instance.new("UICorner", scoreFrame).CornerRadius = UDim.new(0, 8)

local redScore = label({
	parent = scoreFrame,
	size = UDim2.new(0.3, 0, 1, 0),
	position = UDim2.new(0, 0, 0, 0),
	text = "0",
	color = RED,
	textSize = 24,
})
local timerLabel = label({
	parent = scoreFrame,
	size = UDim2.new(0.4, 0, 1, 0),
	position = UDim2.new(0.3, 0, 0, 0),
	text = "5:00",
	textSize = 20,
})
local blueScore = label({
	parent = scoreFrame,
	size = UDim2.new(0.3, 0, 1, 0),
	position = UDim2.new(0.7, 0, 0, 0),
	text = "0",
	color = BLUE,
	textSize = 24,
})

local banner = label({
	size = UDim2.fromOffset(500, 60),
	position = UDim2.new(0.5, 0, 0.35, 0),
	anchor = Vector2.new(0.5, 0.5),
	text = "",
	textSize = 44,
})
banner.Visible = false

roundState.OnClientEvent:Connect(function(data)
	if type(data) ~= "table" then
		return
	end
	redScore.Text = tostring(data.red or 0)
	blueScore.Text = tostring(data.blue or 0)
	timerLabel.Text = string.format("%d:%02d", (data.timeLeft or 0) // 60, (data.timeLeft or 0) % 60)
	if data.state == "over" then
		banner.Visible = true
		if data.winner == "Draw" then
			banner.Text = "DRAW"
			banner.TextColor3 = WHITE
		else
			banner.Text = string.upper(tostring(data.winner)) .. " WINS"
			banner.TextColor3 = data.winner == "Red" and RED or BLUE
		end
	else
		banner.Visible = false
	end
end)

-- Killfeed (top right) ----------------------------------------------------
local feedFrame = Instance.new("Frame")
feedFrame.Size = UDim2.fromOffset(320, 200)
feedFrame.Position = UDim2.new(1, -12, 0, 12)
feedFrame.AnchorPoint = Vector2.new(1, 0)
feedFrame.BackgroundTransparency = 1
feedFrame.Parent = gui

local feedLayout = Instance.new("UIListLayout")
feedLayout.Padding = UDim.new(0, 4)
feedLayout.HorizontalAlignment = Enum.HorizontalAlignment.Right
feedLayout.SortOrder = Enum.SortOrder.LayoutOrder
feedLayout.Parent = feedFrame

local feedOrder = 0
killFeed.OnClientEvent:Connect(function(killerName, victimName, weapon, headshot)
	feedOrder += 1
	local text
	if killerName then
		text = string.format("%s %s %s  [%s]", killerName, headshot and "⌖" or "➤", victimName, weapon or "?")
	else
		text = string.format("%s died", victimName)
	end
	local row = label({
		parent = feedFrame,
		size = UDim2.new(1, 0, 0, 22),
		position = UDim2.new(0, 0, 0, 0),
		text = text,
		textSize = 15,
		bg = true,
		xAlign = Enum.TextXAlignment.Right,
	})
	row.LayoutOrder = feedOrder
	if killerName == player.Name then
		row.TextColor3 = Color3.fromRGB(255, 220, 120)
	end

	-- keep the feed short
	local rows = {}
	for _, child in feedFrame:GetChildren() do
		if child:IsA("TextLabel") then
			table.insert(rows, child)
		end
	end
	table.sort(rows, function(a, b)
		return a.LayoutOrder < b.LayoutOrder
	end)
	for i = 1, #rows - 6 do
		rows[i]:Destroy()
	end

	task.delay(5, function()
		if row.Parent then
			TweenService:Create(row, TweenInfo.new(0.4), { TextTransparency = 1, BackgroundTransparency = 1 }):Play()
			task.delay(0.4, function()
				row:Destroy()
			end)
		end
	end)
end)

-- Character wiring ---------------------------------------------------------
local function watchCharacter(char)
	local humanoid = char:WaitForChild("Humanoid")
	updateHealth(humanoid)
	humanoid.HealthChanged:Connect(function()
		updateHealth(humanoid)
	end)
	setEquipped(nil)
	char.ChildAdded:Connect(function(child)
		if child:IsA("Tool") and child:GetAttribute("WeaponName") then
			setEquipped(child)
		end
	end)
	char.ChildRemoved:Connect(function(child)
		if child == equippedTool then
			setEquipped(nil)
		end
	end)
end

player.CharacterAdded:Connect(watchCharacter)
if player.Character then
	watchCharacter(player.Character)
end
]=],
	},
	{
		parent = { "StarterPlayer", "StarterPlayerScripts", "RivalsClient" },
		name = "MovementClient",
		class = "LocalScript",
		source = [=[
-- Fast movement kit: double jump (Space in mid-air) and dash (Q).
local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")

local player = Players.LocalPlayer
local camera = workspace.CurrentCamera

local DASH_SPEED = 80
local DASH_COOLDOWN = 2
local MAX_AIR_JUMPS = 1

local humanoid, rootPart
local airJumpsUsed = 0
local lastAirJump = 0
local lastDash = 0

local function watchCharacter(char)
	humanoid = char:WaitForChild("Humanoid")
	rootPart = char:WaitForChild("HumanoidRootPart")
	airJumpsUsed = 0
	humanoid.StateChanged:Connect(function(_, newState)
		if newState == Enum.HumanoidStateType.Landed then
			airJumpsUsed = 0
		end
	end)
end

player.CharacterAdded:Connect(watchCharacter)
if player.Character then
	watchCharacter(player.Character)
end

UserInputService.JumpRequest:Connect(function()
	if not (humanoid and humanoid.Health > 0) then
		return
	end
	local now = os.clock()
	if now - lastAirJump < 0.25 then
		return
	end
	if humanoid:GetState() == Enum.HumanoidStateType.Freefall and airJumpsUsed < MAX_AIR_JUMPS then
		lastAirJump = now
		airJumpsUsed += 1
		humanoid:ChangeState(Enum.HumanoidStateType.Jumping)
	end
end)

UserInputService.InputBegan:Connect(function(input, processed)
	if processed then
		return
	end
	if input.KeyCode ~= Enum.KeyCode.Q then
		return
	end
	if not (humanoid and humanoid.Health > 0 and rootPart) then
		return
	end
	local now = os.clock()
	if now - lastDash < DASH_COOLDOWN then
		return
	end
	local dir = humanoid.MoveDirection
	if dir.Magnitude < 0.1 then
		local look = camera.CFrame.LookVector
		dir = Vector3.new(look.X, 0, look.Z)
	end
	if dir.Magnitude < 0.01 then
		return
	end
	lastDash = now
	dir = dir.Unit
	local v = rootPart.AssemblyLinearVelocity
	rootPart.AssemblyLinearVelocity = Vector3.new(dir.X * DASH_SPEED, math.max(v.Y, 12), dir.Z * DASH_SPEED)
end)
]=],
	},
	{
		parent = { "StarterPlayer", "StarterPlayerScripts", "RivalsClient" },
		name = "WeaponClient",
		class = "LocalScript",
		source = [=[
-- Client side of combat: shoulder-locked camera while a weapon is out,
-- crosshair, firing input, tracers, hitmarkers, and reload requests.
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")
local Debris = game:GetService("Debris")

local player = Players.LocalPlayer
local camera = workspace.CurrentCamera

local shared = ReplicatedStorage:WaitForChild("RivalsShared")
local Remotes = require(shared:WaitForChild("Remotes"))
local WeaponConfig = require(shared:WaitForChild("WeaponConfig"))

local fireRemote = Remotes.get("FireWeapon")
local reloadRemote = Remotes.get("Reload")
local hitConfirm = Remotes.get("HitConfirm")

local rng = Random.new()

local character, humanoid, rootPart
local equippedTool, equippedName
local firing = false
local lastShot = 0

-- Crosshair --------------------------------------------------------------
local gui = Instance.new("ScreenGui")
gui.Name = "RivalsCrosshair"
gui.IgnoreGuiInset = true
gui.ResetOnSpawn = false
gui.Enabled = false
gui.Parent = player:WaitForChild("PlayerGui")

local BASE_GAP = 6
local crossSpread = BASE_GAP
local crossFrames = {}
for i = 1, 4 do
	local f = Instance.new("Frame")
	f.BorderSizePixel = 0
	f.BackgroundColor3 = Color3.new(1, 1, 1)
	f.AnchorPoint = Vector2.new(0.5, 0.5)
	f.Parent = gui
	crossFrames[i] = f
end

local function layoutCrosshair()
	local o = math.floor(crossSpread)
	crossFrames[1].Size = UDim2.fromOffset(2, 8)
	crossFrames[1].Position = UDim2.new(0.5, 0, 0.5, -o - 4)
	crossFrames[2].Size = UDim2.fromOffset(2, 8)
	crossFrames[2].Position = UDim2.new(0.5, 0, 0.5, o + 4)
	crossFrames[3].Size = UDim2.fromOffset(8, 2)
	crossFrames[3].Position = UDim2.new(0.5, -o - 4, 0.5, 0)
	crossFrames[4].Size = UDim2.fromOffset(8, 2)
	crossFrames[4].Position = UDim2.new(0.5, o + 4, 0.5, 0)
end
layoutCrosshair()

local function showDamage(amount, headshot)
	local label = Instance.new("TextLabel")
	label.BackgroundTransparency = 1
	label.AnchorPoint = Vector2.new(0.5, 0.5)
	label.Position = UDim2.new(0.5, rng:NextInteger(20, 45), 0.5, rng:NextInteger(-40, -15))
	label.Size = UDim2.fromOffset(80, 24)
	label.Font = Enum.Font.GothamBold
	label.TextSize = headshot and 24 or 18
	label.TextColor3 = headshot and Color3.fromRGB(255, 80, 80) or Color3.fromRGB(255, 220, 120)
	label.TextStrokeTransparency = 0.4
	label.Text = tostring(math.floor(amount + 0.5))
	label.Parent = gui
	TweenService:Create(label, TweenInfo.new(0.6, Enum.EasingStyle.Quad, Enum.EasingDirection.Out), {
		Position = label.Position + UDim2.fromOffset(0, -30),
		TextTransparency = 1,
		TextStrokeTransparency = 1,
	}):Play()
	Debris:AddItem(label, 0.7)
end

hitConfirm.OnClientEvent:Connect(function(damage, headshot)
	showDamage(damage, headshot)
	crossSpread = math.min(crossSpread + 4, 30)
end)

-- Shoulder-lock aiming ----------------------------------------------------
RunService:BindToRenderStep("RivalsAimLock", Enum.RenderPriority.Camera.Value + 1, function()
	local aiming = equippedTool ~= nil and humanoid ~= nil and humanoid.Health > 0 and rootPart ~= nil
	gui.Enabled = aiming
	if aiming then
		UserInputService.MouseBehavior = Enum.MouseBehavior.LockCenter
		UserInputService.MouseIconEnabled = false
		humanoid.CameraOffset = Vector3.new(1.6, 0.4, 0)
		humanoid.AutoRotate = false
		local look = camera.CFrame.LookVector
		local flat = Vector3.new(look.X, 0, look.Z)
		if flat.Magnitude > 0.001 then
			rootPart.CFrame = CFrame.lookAt(rootPart.Position, rootPart.Position + flat)
		end
	else
		UserInputService.MouseBehavior = Enum.MouseBehavior.Default
		UserInputService.MouseIconEnabled = true
		if humanoid then
			humanoid.CameraOffset = Vector3.zero
			humanoid.AutoRotate = true
		end
	end
end)

-- Firing ------------------------------------------------------------------
local function withSpread(dir, degrees)
	if degrees <= 0 then
		return dir
	end
	local cf = CFrame.new(Vector3.zero, dir)
	local pitch = math.rad(rng:NextNumber(-degrees, degrees))
	local yaw = math.rad(rng:NextNumber(-degrees, degrees))
	return (cf * CFrame.Angles(pitch, yaw, 0)).LookVector
end

local function tracer(origin, dir, dist)
	local p = Instance.new("Part")
	p.Anchored = true
	p.CanCollide = false
	p.CanQuery = false
	p.CanTouch = false
	p.Material = Enum.Material.Neon
	p.Color = Color3.fromRGB(255, 220, 120)
	p.Size = Vector3.new(0.08, 0.08, dist)
	p.CFrame = CFrame.lookAt(origin, origin + dir) * CFrame.new(0, 0, -dist / 2)
	p.Parent = workspace
	Debris:AddItem(p, 0.06)
end

local function tryFire()
	local tool, name = equippedTool, equippedName
	if not (tool and name and character and humanoid and humanoid.Health > 0) then
		return
	end
	local cfg = WeaponConfig[name]
	if not cfg then
		return
	end
	local now = os.clock()
	if now - lastShot < 1 / cfg.fireRate then
		return
	end
	if tool:GetAttribute("Reloading") then
		return
	end
	local ammo = tool:GetAttribute("Ammo") or 0
	if ammo <= 0 then
		reloadRemote:FireServer(name)
		return
	end
	local head = character:FindFirstChild("Head")
	if not head then
		return
	end
	lastShot = now

	local params = RaycastParams.new()
	params.FilterDescendantsInstances = { character }
	params.FilterType = Enum.RaycastFilterType.Exclude

	-- Aim through the crosshair: find what the camera is looking at, then
	-- shoot from the head toward that point.
	local camPos = camera.CFrame.Position
	local camResult = workspace:Raycast(camPos, camera.CFrame.LookVector * cfg.range, params)
	local aimPoint = camResult and camResult.Position or (camPos + camera.CFrame.LookVector * cfg.range)

	local origin = head.Position
	local baseDir = aimPoint - origin
	if baseDir.Magnitude < 0.1 then
		return
	end
	baseDir = baseDir.Unit

	local dirs = {}
	for i = 1, cfg.pellets do
		dirs[i] = withSpread(baseDir, cfg.spread)
	end
	fireRemote:FireServer(name, origin, dirs)

	for _, dir in dirs do
		local result = workspace:Raycast(origin, dir * cfg.range, params)
		local dist = result and (result.Position - origin).Magnitude or cfg.range
		tracer(origin, dir, dist)
	end
	crossSpread = math.min(crossSpread + 6, 30)
end

UserInputService.InputBegan:Connect(function(input, processed)
	if processed then
		return
	end
	if input.UserInputType == Enum.UserInputType.MouseButton1 then
		firing = true
		tryFire()
	elseif input.KeyCode == Enum.KeyCode.R then
		if equippedName then
			reloadRemote:FireServer(equippedName)
		end
	end
end)
UserInputService.InputEnded:Connect(function(input)
	if input.UserInputType == Enum.UserInputType.MouseButton1 then
		firing = false
	end
end)

RunService.Heartbeat:Connect(function(dt)
	if firing and equippedName then
		local cfg = WeaponConfig[equippedName]
		if cfg and cfg.auto then
			tryFire()
		end
	end
	crossSpread += (BASE_GAP - crossSpread) * math.min(dt * 8, 1)
	layoutCrosshair()
end)

-- Character / tool tracking ----------------------------------------------
local function watchCharacter(char)
	character = char
	humanoid = char:WaitForChild("Humanoid")
	rootPart = char:WaitForChild("HumanoidRootPart")
	equippedTool, equippedName = nil, nil
	char.ChildAdded:Connect(function(child)
		if child:IsA("Tool") and child:GetAttribute("WeaponName") then
			equippedTool = child
			equippedName = child:GetAttribute("WeaponName")
		end
	end)
	char.ChildRemoved:Connect(function(child)
		if child == equippedTool then
			equippedTool, equippedName = nil, nil
		end
	end)
end

player.CharacterAdded:Connect(watchCharacter)
if player.Character then
	watchCharacter(player.Character)
end
]=],
	},
}

for _, def in ipairs(scripts) do
	local inst = Instance.new(def.class)
	inst.Name = def.name
	inst.Source = def.source
	inst.Parent = resolvePath(def.parent)
end

print(("[Rivals Shooter] Installed %d scripts. Press Play to test!"):format(#scripts))
